# Generated by Django 5.0.7 on 2024-07-28 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(max_length=100, verbose_name="место выполнения"),
                ),
                ("time", models.TimeField(verbose_name="время выполнения")),
                ("action", models.CharField(max_length=200, verbose_name="действие")),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="приятная привычкиа"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        verbose_name="интервал между привычками в днях"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveSmallIntegerField(
                        verbose_name="время на выполнение в секундах"
                    ),
                ),
                ("is_public", models.BooleanField(verbose_name="публичность")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habit.habit",
                        verbose_name="связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
